# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      api:
        image: 507501/my-createpost-api-dockerhub
        ports:
          - 5000:80
        

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_USERNAME}} --password-stdin
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Apply Database Migrations
      env:
          ConnectionStrings__DefaultConnection: "Server=db11894.public.databaseasp.net; Database=db11894; User Id=db11894; Password=c=7EQa#63?Hg; Encrypt=True; TrustServerCertificate=True; MultipleActiveResultSets=True;"
      run: dotnet ef database update --CreateMyPost src/Infrastructure
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Clean up Docker login credentials
      run: docker logout
